import type { Metadata } from "next";
import "./globals.css";
import LenisProvider from "@/lib/providers/LenisProvider";

export const metadata: Metadata = {
    title: "Velvet Pour",
    description: "Generated by create next app",
    icons: {
        icon: "/images/logo.png", // メインファビコン
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ja">
            <body suppressHydrationWarning={true}>
                <LenisProvider>{children}</LenisProvider>
            </body>
        </html>
    );
}
